### ISSUE TITLE
Question: log volume expectations?

### ISSUE THREAD

**Issue by brettwilliams101** [jamf/SplunkIntegrations#2]
Hi...  we intend to bring our JAMF logs into our Splunk environment.  Are there any estimates of how loud or quiet these log messages will be from a licensing standpoint?

**Comment by nc-wendtb** [comment]
This ultimately depends on what you are pulling in from JAMF and how much data there is. The way the input is setup, it works off of an interval setting which determines how often the input polls the JAMF api. One thing to keep in mind, it grabs all data from the specified search every time. It does not only log changes in the data.

Because of this, I have the input run daily, but this would depend on your environment.
